CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(26) PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'private' CHECK (type IN ('private', 'group')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);